### ISSUE TITLE
Problems with 1.5.1

### ISSUE THREAD

**Issue by trentasis** [jackburton79/agent#24] opened 2017-07-26 17:24 UTC
Hi,

I'm testing 1.5.1 and I have detected some problems:

1.- version tag is not updated appears 1.5 and should be 1.5.1 --> required to modify in main.cpp "const char* version = "1.5";"

2.- in ram inventory is not correct, for example this machines 
   Not Specified 1024 System Memory DDR3 1333 MHz 0 01BD3629 

  Not Specified 0   DDR3 Unknown 1   

  Not Specified 1024   DDR3 1333 MHz 2 CDBC3629 

  Not Specified 0   DDR3 Unknown 3   

  Not Specified 4096   Flash Unknown 4 Not Specified 

show as it has 6GB RAM, when really has 2GB RAM

3.- in ram appears 1025 mb ram, when really has to be 1024

4.- If you have a machine with one ethernet and then you have to replace with another ethernet (different mac address) then machine is not inventoried with new changes (new ethernet), only if you remove the computer from ocs, then is inventoried with new ethernet.
IT seems that is since this commit https://github.com/jackburton79/agent/commit/9f81b9fcc4418fcb282a8476b23e0413a6601aa6

Thanks

**Comment by jackburton79** [comment] 2017-07-26 17:48
1. I realized this after tagging the release, too late.
2 & 3. I will have a look.
4. If I understood the problem correctly, I suspect this is a bug in ocs server, since I had the same problem with the Windows agent.

**Comment by trentasis** [comment] 2017-07-26 18:10
Ok, about last question, do you have solved?
With previous version, before this commit was working, can you recovert device id based in time to recover this feature?

Thanks

**Comment by jackburton79** [comment] 2017-07-27 10:19
> Ok, about last question, do you have solved?
> With previous version, before this commit was working, can you recovert device id based in time to recover this feature?

Not like that, since it caused duplicated entries for me.
I'll try to reproduce your problem and fix it in another way.

**Comment by trentasis** [comment] 2017-07-28 08:47
Hi,

About 4, I have tested with windows agent (official) and result is the same with latest ocs 1.5.1, I think that could be a bug in ocs server, and in the futur I'll try to upgrade to latest ocs, for me It is correct
If you need I can make test about other issues.

Thanks

**Comment by trentasis** [comment] 2017-07-28 10:53
Hi
 About memory  with dmidecode and lshw we receive:

ts:~# dmidecode  -t memory
# dmidecode 3.0
Getting SMBIOS data from sysfs.
SMBIOS 2.6 present.

Handle 0x0038, DMI type 16, 15 bytes
Physical Memory Array
    Location: System Board Or Motherboard
    Use: System Memory
    Error Correction Type: None
    Maximum Capacity: 4 GB
    Error Information Handle: Not Provided
    Number Of Devices: 4

Handle 0x0039, DMI type 16, 15 bytes
Physical Memory Array
    Location: System Board Or Motherboard
    Use: Flash Memory
    Error Correction Type: None
    Maximum Capacity: 4 MB
    Error Information Handle: Not Provided
    Number Of Devices: 1

Handle 0x003A, DMI type 17, 28 bytes
Memory Device
    Array Handle: 0x0038
    Error Information Handle: Not Provided
    Total Width: 64 bits
    Data Width: 64 bits
    Size: 1024 MB
    Form Factor: DIMM
    Set: 1
    Locator: XMM1
    Bank Locator: Not Specified
    Type: DDR3
    Type Detail: Synchronous
    Speed: 1333 MHz
    Manufacturer: JEDEC ID:80 2C
    Serial Number: 01BD3629
    Asset Tag: Not Specified
    Part Number: 4JTF12864AZ-1G4D1
    Rank: 1

Handle 0x003B, DMI type 17, 28 bytes
Memory Device
    Array Handle: 0x0038
    Error Information Handle: Not Provided
    Total Width: Unknown
    Data Width: Unknown
    Size: No Module Installed
    Form Factor: DIMM
    Set: 1
    Locator: XMM2
    Bank Locator: Not Specified
    Type: DDR3
    Type Detail: Synchronous
    Speed: Unknown
    Manufacturer: JEDEC ID:
    Serial Number: 
    Asset Tag: Not Specified
    Part Number: 
    Rank: Unknown

Handle 0x003C, DMI type 17, 28 bytes
Memory Device
    Array Handle: 0x0038
    Error Information Handle: Not Provided
    Total Width: 64 bits
    Data Width: 64 bits
    Size: 1024 MB
    Form Factor: DIMM
    Set: 2
    Locator: XMM3
    Bank Locator: Not Specified
    Type: DDR3
    Type Detail: Synchronous
    Speed: 1333 MHz
    Manufacturer: JEDEC ID:80 2C
    Serial Number: CDBC3629
    Asset Tag: Not Specified
    Part Number: 4JTF12864AZ-1G4D1
    Rank: 1

Handle 0x003D, DMI type 17, 28 bytes
Memory Device
    Array Handle: 0x0038
    Error Information Handle: Not Provided
    Total Width: Unknown
    Data Width: Unknown
    Size: No Module Installed
    Form Factor: DIMM
    Set: 2
    Locator: XMM4
    Bank Locator: Not Specified
    Type: DDR3
    Type Detail: Synchronous
    Speed: Unknown
    Manufacturer: JEDEC ID:
    Serial Number: 
    Asset Tag: Not Specified
    Part Number: 
    Rank: Unknown

Handle 0x003F, DMI type 17, 28 bytes
Memory Device
    Array Handle: 0x0039
    Error Information Handle: Not Provided
    Total Width: 2 bits
    Data Width: 2 bits
    Size: 4096 kB
    Form Factor: Chip
    Set: None
    Locator: SYSTEM ROM
    Bank Locator: Not Specified
    Type: Flash
    Type Detail: Non-Volatile
    Speed: Unknown
    Manufacturer: Not Specified
    Serial Number: Not Specified
    Asset Tag: Not Specified
    Part Number: Not Specified
    Rank: Unknown


lshw
    *-memory:0
          description: System Memory
          physical id: 38
          slot: System board or motherboard
        *-bank:0
             description: DIMM DDR3 Synchronous 1333 MHz (0,8 ns)
             product: 4JTF12864AZ-1G4D1
             vendor: JEDEC ID:80 2C
             physical id: 0
             serial: 01BD3629
             slot: XMM1
             size: 1GiB
             width: 64 bits
             clock: 1333MHz (0.8ns)
        *-bank:1
             description: DIMM DDR3 Synchronous [empty]
             vendor: JEDEC ID:
             physical id: 1
             slot: XMM2
        *-bank:2
             description: DIMM DDR3 Synchronous 1333 MHz (0,8 ns)
             product: 4JTF12864AZ-1G4D1
             vendor: JEDEC ID:80 2C
             physical id: 2
             serial: CDBC3629
             slot: XMM3
             size: 1GiB
             width: 64 bits
             clock: 1333MHz (0.8ns)
        *-bank:3
             description: DIMM DDR3 Synchronous [empty]
             vendor: JEDEC ID:
             physical id: 3
             slot: XMM4
     *-memory:1 UNCLAIMED
          description: Flash Memory
          physical id: 39
          slot: System board or motherboard
          capacity: 4MiB
        *-bank UNCLAIMED
             description: Chip FLASH Non-volatile
             physical id: 0
             slot: SYSTEM ROM
             size: 4MiB
             width: 2 bits


and I think that the problem is 
Handle 0x0039, DMI type 16, 15 bytes
Physical Memory Array
    Location: System Board Or Motherboard
    Use: Flash Memory
    Error Correction Type: None
    Maximum Capacity: 4 MB
    Error Information Handle: Not Provided
    Number Of Devices: 1



Caption | Description | Capacity (MB) | Purpose | Type | Speed | Slot number | Serial number
-- | -- | -- | -- | -- | -- | -- | --
  | Not Specified | 1024 | System Memory | DDR3 | 1333 MHz | 0 | 01BD3629

  | Not Specified | 0 |   | DDR3 | Unknown | 1 |  

  | Not Specified | 1024 |   | DDR3 | 1333 MHz | 2 | CDBC3629

  | Not Specified | 0 |   | DDR3 | Unknown | 3 |  

  | Not Specified | 4096 |   | Flash | Unknown | 4 | Not Specified


I hope that this can help

Thanks

**Comment by trentasis** [comment] 2017-07-31 11:31
Any scheculed date?

Thanks

**Comment by jackburton79** [comment] 2017-07-31 15:47
Sorry, I'm out of town. Next week will have a look.

Il 31 lug 2017 1:31 PM, "trentasis" <notifications@github.com> ha scritto:

**Comment by trentasis** [comment] 2017-08-02 09:58
OK, thanks!

**Comment by jackburton79** [comment] 2017-08-07 08:42
Could you please attach an XML inventory generated on the machine ?
You can generate it with ocsinventory-agent --nosoftware --local ./
Thanks!

**Comment by trentasis** [comment] 2017-08-07 10:15
Hi,

Attached xml from ocsinventory-agent --nosoftware --local ./
Thanks

2017-08-07 10:42 GMT+02:00 Stefano Ceccherini <notifications@github.com>:

**Comment by trentasis** [comment] 2017-08-07 10:17
It seems taht xml is not uploaded correctly, If you need I can send to your mail...

**Comment by jackburton79** [comment] 2017-08-07 10:25
Sure!

**Comment by trentasis** [comment] 2017-08-07 12:07
mail sended

**Comment by jackburton79** [comment] 2017-08-07 12:50
[103275D8-1185-11DF-BBDA-857B628FD8D3-2009-08-25-00-00-00.txt](https://github.com/jackburton79/agent/files/1204817/103275D8-1185-11DF-BBDA-857B628FD8D3-2009-08-25-00-00-00.txt)

**Comment by jackburton79** [comment] 2017-08-07 12:57
When you say "show as it has 6GB RAM, when really has 2GB RAM", in which field of OcsInventory ?

**Comment by trentasis** [comment] 2017-08-07 13:46
inside vm inventory in memory and also in memory slots:
Caption;Description;Capacity (MB);Purpose;Type;Speed;Slot number;Serial number;
;Not Specified;1024;System Memory;DDR3;1333 MHz;0;CE4849E3;
;Not Specified;0;;DDR3;Unknown;1;;
;Not Specified;1024;;DDR3;1333 MHz;2;CD4849E3;
;Not Specified;0;;DDR3;Unknown;3;;
;Not Specified;4096;;Flash;Unknown;4;Not Specified;

**Comment by trentasis** [comment] 2017-08-08 20:01
If you can't find the source of issue, it could be interesting to revert memory inventory used in version 30/5/2016 that was working and showing correctly, now I'm evaluating to return to this versionm as temporary workarorund
Thanks!

**Comment by jackburton79** [comment] 2017-08-17 06:55
Unfortunately I don't have any machine which exibits this issue.
Could you try to revert commit bd706bb6089150c5e353c89cf6ca798f2b72e10d to see if it fixes your problem ?

**Comment by trentasis** [comment] 2017-08-22 17:10
OK, I'll try to make some test with this version

2017-08-17 8:55 GMT+02:00 Stefano Ceccherini <notifications@github.com>:

**Comment by trentasis** [comment] 2017-08-22 18:28
Tried with https://github.com/jackburton79/agent/commit/bd706bb6089150c5e353c89cf6ca798f2b72e10d with same result, incorrect value ram

**Comment by jackburton79** [comment] 2017-10-23 18:36
Hi, could you test the current master to see if it fixes this problem (wrong memory reported) ?

**Comment by jackburton79** [comment] 2017-10-24 17:23
I think this is fixed in the master branch.

**Closed** 2017-10-31 14:03 UTC

**Comment by trentasis** [comment] 2018-01-18 19:33
It works!
Thanks

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-10-31 15:03 GMT+01:00 Stefano Ceccherini <notifications@github.com>:
